authors:
  alina-derkach-oaza:
    name: Alina Derkach
    description: Senior Technical Writer
    avatar: https://avatars.githubusercontent.com/u/81975178
    url: https://github.com/alina-derkach-oaza
  patrickbirch:
    name: Patrick Birch
    description: Principal Technical Writer
    avatar: https://avatars.githubusercontent.com/u/48594400
    url: https://github.com/patrickbirch
  nastena1606:
    name: Anastasia Alexandrova
    description: Senior Technical Writer
    avatar: https://avatars.githubusercontent.com/u/60600800
    url: https://github.com/nastena1606
  catalinaadam:
    name: Catalina Adam
    description: Senior Technical Writer
    avatar: https://avatars.githubusercontent.com/u/94133018
    url: https://github.com/catalinaadam
  rasika-chivate:
    name: Rasika Chivate
    description: Technical Writer
    avatar: https://avatars.githubusercontent.com/u/95711051
    url: https://github.com/rasika-chivate
  Andriciuc:
    name: Dragos Andriciuc
    description: Senior Technical Writer
    avatar: https://avatars.githubusercontent.com/u/9531841
    url: https://github.com/Andriciuc/
  spron-in:
    name: Sergey Pronin
    description: Group Product Manager
    avatar: https://avatars.githubusercontent.com/u/11819154
    url: https://github.com/spron-in
  fiowro:
    name: Dmitriy Kostiuk
    description: Senior Technical Writer
    avatar: https://avatars.githubusercontent.com/u/147437
    url: https://github.com/fiowro

  